from setuptools import setup, find_packages

setup(
    name="nornir-detect",
    version="0.1.0",
    description="Nornir plugin for automatic network device detection using device-detect module",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Mohamed RABAH",
    author_email="mdrbh0@gmail.com",
    url="https://github.com/mdrbh0/nornir-detect",
    packages=find_packages(),
    install_requires=[
        "nornir>=3.0.0",
        "device-detect>=0.7.0",
    ],
    extras_require={
        "netmiko": ["nornir-netmiko"],
        "scrapli": ["nornir-scrapli"],
        "napalm": ["nornir-napalm"],
        "salt": ["nornir-salt"],
        "ansible": ["nornir-ansible"],
        "utils": ["nornir-utils"],
        "full": [
            "nornir-netmiko",
            "nornir-scrapli",
            "nornir-napalm",
            "nornir-salt",
            "nornir-ansible",
            "nornir-utils",
        ],
    },
    python_requires=">=3.7",
    license="MIT",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: System :: Networking",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords=["nornir", "network", "automation", "detection", "device-detect"],
)
